platform :ios, '10.0'
inhibit_all_warnings!
use_frameworks!

target 'Demo' do
  pod 'Moya'
  pod 'Cache'
  pod 'MBProgressHUD'
  pod 'GGUI'
  pod 'DZNEmptyDataSet'
  pod 'PullToRefreshKit'

  pod 'SwiftLint'
end
