platform :ios, '10.0'
inhibit_all_warnings!
use_frameworks!

target 'Demo' do
        
    # Tool
    pod 'SwiftLint'
    pod 'FLEX'

    # Sources dependency
    pod 'GGUI', :path => '~/Work/ganguo/Swift/DevelopPods/GGUI'
    pod 'Moya'
    pod 'Cache'
    pod 'PullToRefreshKit'
end
